
import { Geist, Geist_Mono, Imprima } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar"
// import Loader from "@/app/components/Loader";
// import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Webo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = typeof window !== "undefined" ? window.location.pathname : ""
  return (
    <html lang="en">
      <body

      >
        
         <Navbar />
        <main className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* <Suspense fallback={<Loader />}> */}
          {children}
          {/* </Suspense> */}
        </main>

      </body>
    </html>
  );
}
